/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    03LoginLogin: typeof import('./src/components/03Login/Login.vue')['default']
    Login: typeof import('./src/components/03Login/Login.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
